<?php

return [
    // Common Indonesian cities and regencies (can be extended)
    'cities' => [
        'Aceh Barat','Aceh Besar','Aceh Jaya','Aceh Selatan','Aceh Tengah','Aceh Tenggara','Aceh Timur','Aceh Utara','Banda Aceh','Bener Meriah',
        'Bireuen','Sabang','Langsa','Lhokseumawe','Pidie','Pidie Jaya','Simeulue','Subulussalam',
        'Bandung','Bekasi','Bogor','Cimahi','Depok','Sukabumi','Tasikmalaya','Cirebon','Banjar',
        'Semarang','Surakarta (Solo)','Magelang','Salatiga','Pemalang' ,'Pekalongan','Tegal','Purwokerto',
        'Jakarta','Surabaya','Sidoarjo','Malang','Kediri','Madiun','Banyuwangi','Bojonegoro','Jember',
        'Yogyakarta','Bantul','Sleman','Kulon Progo','Gunungkidul',
        'Bandar Lampung','Metro','Pematangsiantar','Medan','Binjai','Tebing Tinggi','Padang','Bukittinggi',
        'Palembang','Lubuk Linggau','Prabumulih','Bengkulu','Jambi','Pekanbaru','Dumai','Riau',
        'Banjarmasin','Banjarbaru','Palangka Raya','Samarinda','Balikpapan','Bontang','Tarakan','Sanggau',
        'Manado','Bitung','Tomohon','Gorontalo','Palu','Kendari','Ambon','Tual','Kupang','Kupang Kota',
        'Mataram','Bima','Sumbawa','Denpasar','Singaraja','Makasar','Parepare','Bulukumba','Luwu',
        'Pontianak','Singkawang','Bengkayang','Tanjung Pinang','Batam','Tanjung Balai Karimun','Padang Sidempuan',
        'Sorong','Jayapura','Biak','Merauke','Manokwari','Timika','Sabang','Bau-Bau','Baubau'
    ],
    // Provinces of Indonesia
    'provinces' => [
        'Aceh',
        'Sumatera Utara',
        'Sumatera Barat',
        'Riau',
        'Kepulauan Riau',
        'Jambi',
        'Bengkulu',
        'Sumatera Selatan',
        'Kepulauan Bangka Belitung',
        'Lampung',
        'Banten',
        'DKI Jakarta',
        'Jawa Barat',
        'Jawa Tengah',
        'DI Yogyakarta',
        'Jawa Timur',
        'Bali',
        'Nusa Tenggara Barat',
        'Nusa Tenggara Timur',
        'Kalimantan Barat',
        'Kalimantan Tengah',
        'Kalimantan Selatan',
        'Kalimantan Timur',
        'Kalimantan Utara',
        'Sulawesi Utara',
        'Sulawesi Tengah',
        'Sulawesi Selatan',
        'Sulawesi Tenggara',
        'Gorontalo',
        'Maluku',
        'Maluku Utara',
        'Papua',
        'Papua Barat',
    ],
];
